### ISSUE TITLE
cdn 资源加载不了 打不开

### ISSUE THREAD

**Issue by chenxu-javascript** [lin-mt/json-schema-editor-arco#1]
<img width="1480" alt="image" src="https://user-images.githubusercontent.com/16332458/182009897-15e6b396-a78f-482b-a7f1-0ff1e15153c6.png">

**Comment by lin-mt** [comment]
<img width="1618" alt="image" src="https://user-images.githubusercontent.com/58337359/182013537-461f1a46-240d-4831-8d36-8bed8dfd524e.png">

可以的哦～
把梯子关了再试试哈
